apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-hello-app.fullname" . }}
  labels:
    {{- include "k8s-hello-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    {{- include "k8s-hello-app.selectorLabels" . | nindent 4 }}
